### PR TITLE
[#212] Consider only textual elements before OCR relaunch at zero texts

### LINKED ISSUE #212: Autodetection of scanned document doesn't work anymore
**Summary**
The autodetection of scanned document seems to be broken.
Code here: https://github.com/axa-group/Parsr/blob/master/server/bin/index.ts#L120-L121

**Steps To Reproduce**
1. Send a scanned PDF with only images in it (no text).

**Expected behavior**
The [program](https://github.com/axa-group/Parsr/blob/master/server/bin/index.ts#L120-L121) should be able to detect that no text has been properly extracted and re-run everything using an OCR.

**Actual behavior**
No detection is made, so no text is outputed (or maybe only whitespaces).

**Environment**
On `develop` branch.

**Additional context**
I tried with the good-old sample4.pdf.

### PR DESCRIPTION
**Pull request by aarohijohal**
Resolves #212

When we start OCRing all the images inside a pdf, the part `- p.getElementsOfType(Image).length` from the following should be removed:
https://github.com/axa-group/Parsr/blob/274bcc10e74cb00b8af7a6a1f2b18a11edf86783/server/bin/index.ts#L130-L131

### CODE REVIEW

File: server/bin/index.ts [hunk 1]
```diff
@@ -125,7 +125,10 @@ function main(): void {
     orchestrator
       .run(filePath)
       .then((doc: Document) => {
-        const nbTexts = doc.pages.map(p => p.elements.length).reduce((a, b) => a + b, 0);
+        // TODO: when we start OCRing all the images inside a pdf, the part '- p.getElementsOfType(Image).length'
+        // should be removed
+        const nbTexts = doc.pages.map(p => p.elements.length - p.getElementsOfType(Image).length)
```
Comment (jvalls-axa) [inline server/bin/index.ts]: Hi @aarohijohal 
Could be better this approach ?? And remove the TODO ??
`const nbTexts = doc.getElementsOfType(Word, true).length;`

Then when we start to OCRing images found in text based pdf we will don't need to update this code, right ?

Comment (aarohijohal) [reply server/bin/index.ts]: Excellent suggestion! But we could always have a document without any words and only tables containing barcodes for example.

Comment (jvalls-axa) [reply server/bin/index.ts]: As we commented please try to find best & understandable code to detect image based pds's

Comment (aarohijohal) [reply server/bin/index.ts]: Done in ee62014
