### PR TITLE
Fix/incorrect font size tesseract abbyy

### LINKED ISSUE #211: Font-size is always 0px on the Vue demo with Tesseract
**Summary**
When sending a PDF with only images (such as a scan) and using TesseractExtractor, the font-size is always 0px so the text is invisible on the web interface.

**Steps To Reproduce**
1. Send a scanned document to the pipeline from the Vue Web Demo
2. Wait and have a look at the Document Viewer

**Expected behavior**
To be able to read the extracted text.

**Actual behavior**
Nothing shows because font-size is 0.

**Additional context**
I tried on the `develop` branch.

### PR DESCRIPTION
**Pull request by marianorodriguez**
fixes #211 

related to clubhouse story ID [#3504](https://app.clubhouse.io/parsr/story/3504/ui-pipeline-improvement)

- On Tesseract, sets the font-size to the Word's BoundingBox height multiplied by 1.6
- On ABBYY, changes the font-size unit to 'em' instead of 'px'

Before: seemingly blank pages.

After - Tesseract:
Screenshot 2019-11-21 at 15 16 41

After - ABBYY:
Screenshot 2019-11-21 at 15 16 14

### CODE REVIEW

File: demo/vue-viewer/src/components/Thumbnails.vue [hunk 1]
```diff
@@ -61,6 +62,12 @@ export default {
       this.thumbClicked(index, false);
     },
   },
+  computed: {
+    ...mapState(['inputFileName']),
+    canShowThumbnails() {
+      return this.inputFileName.split('.').pop() === 'pdf';
```
Comment (jvalls-axa) [inline demo/vue-viewer/src/components/Thumbnails.vue]: If we upload an image ?? Will not be shown ??

🤔

Comment (marianorodriguez) [reply demo/vue-viewer/src/components/Thumbnails.vue]: solved in 67b7256
