### PR TITLE
[Issue-186] Skip white font color

### LINKED ISSUE #186: White Text Not Rendered On Demo Web View
**Summary**

When one upload a PDF with selectable white text, the Web View renders it with white on white, making it unreadable.

**Steps To Reproduce**
1. Get a PDF with white text
2. Upload it
3. You will not see the text but you can hover it and select it

**Expected behavior**
Text should be readable, maybe by:
- changing the background of the white text
- changing the background of the page
- rendering just the outline/stroke of the text

**Actual behavior**
Text is unreadable.

**Screenshots**

Capture d’écran 2019-11-01 à 11 37 38
Capture d’écran 2019-11-01 à 11 38 31

**Environment**
 - Reference commit/version: [2488b93]  (HEAD -> develop)

**Additional context**
The file was the good old t2.pdf

### PR DESCRIPTION
**Pull request by jvalls-axa**
Fix #186 

Please close bug when PR is approved

### CODE REVIEW

File: demo/vue-viewer/src/components/DocumentPreview/Word.vue [hunk 1]
```diff
@@ -1,68 +1,43 @@
...
+      :y="props.element.box.t + props.element.box.h"
+      :textLength="props.element.box.w"
+      :lengthAdjust="
+        props.fonts.filter(font => font.id === props.element.font).shift().size
+          ? 'spacing'
+          : 'spacingAndGlyphs'
+      "
+      :style="{
+        fontSize: props.fonts.filter(font => font.id === props.element.font).shift().size * 0.6,        
+        fill: props.fonts.filter(font => font.id === props.element.font).shift().color != '#ffffff' ? props.fonts.filter(font => font.id === props.element.font).shift().color : '#000',
```
Comment (BinaryBrain) [inline demo/vue-viewer/src/components/DocumentPreview/Word.vue]: Note that it will not work if the color is `#fffeff` for instance.
